repos:
  - repo: local
    hooks:
      - id: sqlx-prepare
        name: cargo sqlx prepare
        entry: bash -c 'cargo sqlx prepare -- --all-targets && git add .sqlx'
        language: system
        pass_filenames: false
        files: \.(rs|sql)$
